// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kltmhbvhcsebpufckern.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsdG1oYnZoY3NlYnB1ZmNrZXJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MDA2MTEsImV4cCI6MjA2ODE3NjYxMX0.vF3QaE86WJyavDpXw63xKH0Cfr9C837tnaZKyBhCXdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});